version: "3.8"

services:
 web:
  build:
   context: .
   dockerfile: Dockerfile
  image: nitrocc/webrium:1.0.4
  volumes:
   - ./src/:/var/www/html/
   - vendor:/var/www/html/vendor
  ports:
   - 8080:80
 db:
  image: mariadb:10.6
  environment:
   - MARIADB_ROOT_PASSWORD=123456
 phpmyadmin:
  image: phpmyadmin:latest
  ports:
   - 8081:8081
  environment:
   - APACHE_PORT=8081

volumes:
 vendor:
 
